name: Run Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache eggs
      uses: actions/cache@v2
      with:
        path: |
          eggs
          buildout-cache
        key: eggs-${{ matrix.python-version }}-${{ hashFiles('ci.cfg') }}
        restore-keys: eggs-${{ matrix.python-version }}
    - name: Install zc.buildout
      run: pip install -r https://dist.plone.org/release/5.2-latest/requirements.txt
    - name: Bootstrap zc.buildout
      run: buildout bootstrap
    - name: Run buildout
      run: bin/buildout
    - name: Run tests
      run: bin/test
